route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  receiver: "telegram"
receivers:
  - name: 'telegram'
    telegram_configs:
    - bot_token: '6978967410:AAESIP6ZjYNDipKJ4dW4h_TQyjjYCnsrSZg'
      chat_id: -4774711082

