global:
  resolve_timeout: 1m
route:
  group_by: ['alertname']
  group_wait: 1m  
  group_interval: 1m
  receiver: "slack"

receivers:
  - name: 'telegram'
    telegram_configs:
    - bot_token: '6978967410:AAESIP6ZjYNDipKJ4dW4h_TQyjjYCnsrSZg'
      chat_id: -4774711082


  - name: 'slack'
    slack_configs:
    - api_url: 'https://hooks.slack.com/services/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'
      channel: '#alerts' 
      send_resolved: true
      text: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
