services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus  
    hostname: prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml  
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring    
    ports:
      - 9090:9090
  
  alert-manager:
    container_name: alert-manager
    hostname: alertmanager  
    image: prom/alertmanager:latest
    volumes:
      - ./alertmanager:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    networks:
      - monitoring
    ports:
      - 9093:9093

  node-exporter:
    container_name: node-exporter
    hostname: node  
    image: prom/node-exporter:latest
    networks:
      - monitoring
    ports:
      - 9100:9100 
        
networks:
  monitoring:
    name: monitoring
    driver: bridge
