groups:
- name: cpu-alert
  rules:
  - alert: HighCPU
    #expr: (100 - (avg(irate(node_cpu_seconds_total{mode="idle"}[1m])) * 100)) > 98
    expr: avg(rate(node_cpu_seconds_total{mode="idle"}[1m])) by (instance) < 0.9999
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "CPU {{ $value | printf \"%.2f\" }}%! сервер {{ $labels.instance }} перегружен"
- name: instanse-down
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 1m
